version: '3.8'

services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault_dev
    ports:
      - "8200:8200" # Exponer el puerto de Vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root-token" # Token raíz para desarrollo
      VAULT_ADDR: "http://127.0.0.1:8200"
    command: server -dev -dev-root-token-id="root-token"
    volumes:
      - ./vault/data:/vault/data # Persistencia de datos
      - ./vault/config:/vault/config # Configuraciones personalizadas
    restart: unless-stopped
