version: '3.7'
services:
  vault:
    image: hashicorp/vault:latest
    container_name: ansible_vault_dev
    ports:
      - "35013:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root-token
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_API_ADDR=http://127.0.0.1:8200
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault/data:/vault/file
      - ./vault/config:/vault/config
      - ./vault/logs:/vault/logs
