---
# ╔══════════════════════════════════════════════════════════════╗
# ║  MAIN ROUTER - Punto de Entrada Principal de Ansible       ║
# ║  Versión: 2.0.0 - 100% HashiCorp Vault                      ║
# ║  Uso: ansible-playbook main.yml -e "mode=vmware"           ║
# ║  Requiere: Docker con Vault corriendo en puerto 8200       ║
# ╚══════════════════════════════════════════════════════════════╝

- name: "🎯 MAIN ROUTER - Orquestación Centralizada con Vault"
  hosts: localhost
  connection: local
  gather_facts: yes
  become: no
  
  vars:
    # 🌍 Información del Proyecto
    project_name: "Infraestructura Ansible - vCenter"
    project_version: "1.0.0"
    environment: "{{ env | default('staging') }}"
    
    # 📝 Modos de ejecución disponibles
    available_modes:
      - vmware              # Gestión de vCenter y VMs
      - provisioning        # Provisioning en VMs Linux/Windows
      - monitoring          # Monitoreo de sistemas
      - maintenance         # Tareas de mantenimiento
      - backup              # Respaldos
      - security            # Endurecimiento de seguridad
  
  pre_tasks:
    # 🎨 Banner de inicio
    - name: "📊 Mostrar banner de inicio"
      debug:
        msg: |
          ╔════════════════════════════════════════════════════════════╗
          ║         🚀 ANSIBLE MAIN ROUTER - vCenter Edition 🚀         ║
          ╠════════════════════════════════════════════════════════════╣
          ║ Proyecto: {{ project_name }}
          ║ Versión: {{ project_version }}
          ║ Ambiente: {{ environment }}
          ║ Modo: {{ mode | default('help') | upper }}
          ║ Usuario: {{ ansible_user_id }}
          ║ Fecha/Hora: {{ ansible_date_time.iso8601 }}
          ║ Versión Ansible: {{ ansible_version.full }}
          ╚════════════════════════════════════════════════════════════╝
      tags:
        - always

    # 🔍 Validar modo
    - name: "🔍 Validar modo de ejecución"
      assert:
        that:
          - mode is defined
          - mode in available_modes
        fail_msg: |
          ❌ ERROR: Modo '{{ mode | default('NO ESPECIFICADO') }}' no válido

          📋 Modos disponibles:
          {% for m in available_modes %}
          ✓ ansible-playbook main.yml -e "mode={{ m }}"
          {% endfor %}
          
          💡 Ejemplo con ambiente específico:
          ✓ ansible-playbook main.yml -e "mode=vmware env=production"
      tags:
        - always
    
    # 📚 Mostrar ayuda si no hay modo
    - name: "❓ Mostrar ayuda"
      debug:
        msg: |
          ℹ️  AYUDA - USO DEL ROUTER PRINCIPAL:

          🎯 EJECUCIÓN BÁSICA:
          ansible-playbook main.yml -e "mode=vmware"
          ansible-playbook main.yml -e "mode=provisioning"
          ansible-playbook main.yml -e "mode=monitoring"
          ansible-playbook main.yml -e "mode=maintenance"
          ansible-playbook main.yml -e "mode=backup"
          ansible-playbook main.yml -e "mode=security"

          🌍 CON AMBIENTE ESPECÍFICO:
          ansible-playbook main.yml -e "mode=vmware env=production"
          ansible-playbook main.yml -e "mode=provisioning env=staging"

          🔍 CON VERBOSIDAD:
          ansible-playbook main.yml -e "mode=vmware" -vv

          ✅ MODO SEGURO (Dry-run):
          ansible-playbook main.yml -e "mode=provisioning" --check

          🏷️  CON TAGS:
          ansible-playbook main.yml -e "mode=vmware" -t vcenter

          💾 SALVAR OUTPUT:
          ansible-playbook main.yml -e "mode=vmware" > output.log 2>&1

          🔑 CON VAULT:
          ansible-playbook main.yml -e "mode=vmware" --ask-vault-pass
      when: mode is not defined
      tags:
        - always
  
  tasks:
    # 🔌 VMWARE - Gestión de vCenter
    - name: "🔌 Ejecutar gestión de vCenter"
      include_tasks: playbooks/vmware.yml
      when: mode == 'vmware'
      tags:
        - vmware
        - vcenter
        - infrastructure
    
    # 📦 PROVISIONING - Deploy en VMs
    - name: "📦 Ejecutar provisioning"
      include_tasks: playbooks/provisioning.yml
      when: mode == 'provisioning'
      tags:
        - provisioning
        - deploy
        - infrastructure
    
    # 📊 MONITORING - Monitoreo
    - name: "📊 Ejecutar monitoreo"
      include_tasks: playbooks/monitoring.yml
      when: mode == 'monitoring'
      tags:
        - monitoring
        - observability
    
    # 🔧 MAINTENANCE - Mantenimiento
    - name: "🔧 Ejecutar mantenimiento"
      include_tasks: playbooks/maintenance.yml
      when: mode == 'maintenance'
      tags:
        - maintenance
        - operations
    
    # 💾 BACKUP - Respaldos
    - name: "💾 Ejecutar respaldos"
      include_tasks: playbooks/backup.yml
      when: mode == 'backup'
      tags:
        - backup
        - data-protection
    
    # 🔐 SECURITY - Seguridad
    - name: "🔐 Ejecutar endurecimiento de seguridad"
      include_tasks: playbooks/security.yml
      when: mode == 'security'
      tags:
        - security
        - hardening
  
  post_tasks:
    # ✅ Resumen final
    - name: "✅ Mostrar resumen final"
      debug:
        msg: |
          ╔════════════════════════════════════════════════════════════╗
          ║              ✅ EJECUCIÓN COMPLETADA CON ÉXITO             ║
          ╠════════════════════════════════════════════════════════════╣
          ║ Modo: {{ mode | upper }}
          ║ Ambiente: {{ environment | upper }}
          ║ Resultado: SUCCESS ✓
          ║ Fin: {{ ansible_date_time.iso8601 }}
          ╚════════════════════════════════════════════════════════════╝
      tags:
        - always