---
# roles from Ansible Galaxy
roles:
  # Módulo 1: Usuarios y Permisos
  - name: robertdebock.users
  - name: linux-system-roles.sudo

  # Módulo 2: Seguridad y Firewall
  - name: geerlingguy.security
  - name: geerlingguy.firewall

  # Módulo 3: Automatización
  - name: robertdebock.service

  # Módulo 4: Provisioning VMs
  - name: geerlingguy.docker
  - name: geerlingguy.nginx

  # Módulo 6: Storage
  - name: linux-system-roles.storage

# collections from Ansible Galaxy
collections:
  # Módulo 2: Seguridad (para gestión de VMware)
  - name: community.vmware

  # Módulo 4: Provisioning (para Windows)
  - name: ansible.windows
  - name: community.general
